name: my_vpn_app
description: A VPN application for mobile.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # เราจะเพิ่ม Library สำหรับ VPN เข้าไปในอนาคตครับ