name: Build Flutter App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - run: |
          # บังคับกำหนดชื่อโปรเจกต์ด้วย --project-name เพื่อแก้ปัญหาขีดกลาง (-)
          flutter create --project-name=my_vpn_app .
          
          # ตั้งค่าเวอร์ชัน Android
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 26/g' android/app/build.gradle
          sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/g' android/app/build.gradle
          sed -i 's/targetSdkVersion flutter.targetSdkVersion/targetSdkVersion 34/g' android/app/build.gradle
          
          # Build
          flutter pub get
          flutter build apk --split-per-abi --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/